### ISSUE TITLE
Test that a Felt is zero

### ISSUE THREAD

**Issue by gabrielbosio** [lambdaclass/cairo-vm_in_go#117]
Add tests for the `Felt.IsZero` method to ensure the following two cases:

- The method returns `true` when it receives a `Felt` that has all its limbs set to 0.
- The method returns `false` when it receives a `Felt` that has all at least one limb set to a non-zero value.

The method is defined [here](https://github.com/lambdaclass/cairo-vm.go/blob/736c56caff01310f17ee35cb8d8ac5e1e8e28766/pkg/lambdaworks/lambdaworks.go#L99).

**Comment by mattcoburn24** [comment]
hey @gabrielbosio , can i work on this issue?

**Comment by gabrielbosio** [comment]
@coburn24 sure!

**Comment by coburn24** [comment]
thanks @gabrielbosio Let me know if this needs PR needs anything changed 🙂
