### ISSUE TITLE
Test relocatable equality

### ISSUE THREAD

**Issue by gabrielbosio** [lambdaclass/cairo-vm_in_go#118]
Add tests for the `Relocatable.IsEqual` method to ensure the correct behavior in the following two cases:

- When two `Relocatable`s have the same field values the method returns `true`.
- When two `Relocatable`s have different field values the method returns `false`.

The method is defined [here](https://github.com/lambdaclass/cairo-vm.go/blob/736c56caff01310f17ee35cb8d8ac5e1e8e28766/pkg/vm/memory/relocatable.go#L75-L77).

**Comment by mattcoburn24** [comment]
Hey @gabrielbosio I have a PR ready for this issue. is it better to wait until morning to `git rebase master` after other commits have been merged, or can i just submit a PR when i resolve an issue? Does it makes a difference on your end when it comes to merging PRs?

**Comment by gabrielbosio** [comment]
Hi, @coburn24, thanks for contributing!
In this case, because the issues involve adding tests, we can ensure that the PRs are independent from each other, so you can open another PR without any problem.
