### ISSUE TITLE
Test segment relocation without computing segment sizes before

### ISSUE THREAD

**Issue by gabrielbosio** [lambdaclass/cairo-vm_in_go#121]
Test `MemorySegmentManager.RelocateSegments` method without computing segment sizes before. The test should expect the method to return `nil, false`.

To achieve this, [the first condition in the method](https://github.com/lambdaclass/cairo-vm.go/blob/736c56caff01310f17ee35cb8d8ac5e1e8e28766/pkg/vm/memory/segments.go#L44) must be fixed. It should be `len(m.SegmentSizes) == 0` instead of `m.SegmentSizes == nil`.

The method is defined [here](https://github.com/lambdaclass/cairo-vm.go/blob/736c56caff01310f17ee35cb8d8ac5e1e8e28766/pkg/vm/memory/segments.go#L43-L58).

**Comment by toni-calvin** [comment]
This would never happen because it will only return nil, false when the SegmentSizes map is nil, and it will never be nil because when initializating a new MemorySegmentManager it initialises the map too. And RelocateSegments only can be called when a MemorySegmentManager is initialised

**Comment by gabrielbosio** [comment]
Updated. Thanks, Toni!
