### ISSUE TITLE
Add `dict` module hints

### ISSUE THREAD

**Issue by entropidelic** [lambdaclass/cairo-vm_in_go#188]
- [ ] `DEFAULT_DICT_NEW` 
- [ ] `DICT_NEW`
- [ ] `DICT_READ`
- [ ] `DICT_WRITE` 
- [ ] `DICT_UPDATE`
- [ ] `DICT_SQUASH_COPY_DICT`
- [ ] `DICT_SQUASH_UPDATE_PTR`

**Comment by fmoletta** [comment]
DICT_SQUASH hints depend on SQUASH_DICT hints, so this issue will be paused in the meantime while I work on #196
