### ISSUE TITLE
Make demo presentable

### ISSUE THREAD

**Issue by gabrielbosio** [lambdaclass/cairo-vm_in_go#59]
Add some print statements to the CLI, something to show that the trace and memory files are the same as the ones generated with the Rust implementation.

**Comment by fmoletta** [comment]
> something to show that the trace and memory files are the same as the ones generated with the Rust implementation.

You mean the `compare_trace_memory target`?

**Comment by gabrielbosio** [comment]
> You mean the compare_trace_memory target?

Yes
