### ISSUE TITLE
Document MemorySegmentManager

### ISSUE THREAD

**Issue by gabrielbosio** [lambdaclass/cairo-vm_in_go#85]

**Comment by fmoletta** [comment]
Its here https://github.com/lambdaclass/cairo-vm.go#memorysegmentmanager

**Comment by fmoletta** [comment]
The high level overview also goes over the memory segment manager methods in  the memory api section https://github.com/lambdaclass/cairo-vm.go#memory-api.
This corresponds to the c implementation where we merged both structs to reduce complexity so maybe we could mention that it encapsulates both behaviours

**Comment by gabrielbosio** [comment]
Yes, sorry. I will close it.
